### ISSUE TITLE
NaN sometimes

### ISSUE THREAD

**Issue by pedz** [judofyr/duktape.rb#37] opened 2017-04-22 17:37 UTC
This could easily be the wrong place for this "issue".

I'm using Duktape to precompile my assets for a Rails 3 application.  I'm developing on a Mac so I don't need Duktape on the Mac but I am deploying to AIX and I need Duktape there.  

To recreate the issue I have in production, I need to do
    config.assets.debug = false
in development mode and then precompile the assets.

If I don't use Duktape, things work (on the Mac).  If I use Duktape, they do not.  I get an error at load time from the browser.  The difference in the two versions is the working version has toJSON while the non-working version produced by Duktape has NaN.  There are many instances similar to this.

I'm using the "master" fork from this git repository.

**Comment by judofyr** [comment] 2017-04-28 10:54
This is very strange and I'm not quite sure how to debug it. Do you have a smaller Ruby/Rails program which shows this behaviour?

**Comment by pedz** [comment] 2017-04-28 12:50
Not yet but that is an interesting idea.  Let me make a copy of my current project and just start deleting stuff.  It may be that when I delete something in particular, it avoids the issue and that might give us a clue as to what is wrong.

I’ll try and find time to do that this weekend.

**Comment by judofyr** [comment] 2018-05-21 08:29
Closing this until you can figure out the root cause

**Closed by judofyr** 2018-05-21 08:29 UTC
